services:
  tap-hoa-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tap-hoa-fe
    restart: always
    networks:
      - my-networks
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 9999:3000
