services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nails-fe
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 8888:3000